title: "&cTérképbeállítások"
type: HOPPER

options:
  scoreboard:
    slot: 0
    material: PAPER
    lore: |
      &7Megjeleníti a királyság térképét
      eredménytáblaként ami kényelmesebb,
      mint az automatikus térkép mód, és
      automatikusan frissül.

      Hátránya, hogy a képernyő hatalmas
      részét foglalja el és meg kell
      jegyezned a szimbólumokat és a
      színeket és azok jelentését.

      Ez az opció visszaáll, ha kilépsz.
    enabled:
      condition: scoreboard_enabled
      name: "{$enabled} Eredménytábla átkapcsolása"
      glow: true
    else:
      name: "{$disabled} Eredménytábla átkapcsolása"
  reset:
    slot: 1
    material: PLAYER_HEAD
    name: '&4Beállítások visszaállítása'

    # https://minecraft-heads.com/custom-heads/alphabet/45282-redstone-block-refresh
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzA1ZWI3ZTA0ODg2ODMyNTRlZGI2NzgyYzVkYjhkMjdjZDA3OGU3ODRkZTJkY2RjZDI1Y2UwODY0ZGZhYmQzOCJ9fX0='
  resize:
    slot: 2
    material: PLAYER_HEAD
    name: '&2Átméretezés'
    lore:
      - "&7Saját térképed méretének módosítása &awidth &7és &aheight"
      - "&7Aktuális méret&8: &2%kingdoms_map_width%&7, &2%kingdoms_map_height%"

    # https://minecraft-heads.com/custom-heads/decoration/49973-globe
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODc5ZTU0Y2JlODc4NjdkMTRiMmZiZGYzZjE4NzA4OTQzNTIwNDhkZmVjZDk2Mjg0NmRlYTg5M2IyMTU0Yzg1In19fQ=='
  auto:
    slot: 3
    material: PLAYER_HEAD
    lore:
      - "&7A térkép automatikusan megjelenik"
      - "ahogy különböző területekre sétálsz."

    enabled:
      condition: 'auto_map_enabled'
      name: "{$enabled} Auto"
      # https://minecraft-heads.com/custom-heads/alphabet/21774-green-checkmark
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDMxMmNhNDYzMmRlZjVmZmFmMmViMGQ5ZDdjYzdiNTVhNTBjNGUzOTIwZDkwMzcyYWFiMTQwNzgxZjVkZmJjNCJ9fX0='
    else:
      name: "{$disabled} Auto"
      # https://minecraft-heads.com/custom-heads/miscellaneous/44761-x
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDdhY2ZmNThjMjExZTQ2ODA2ZDRhYzlhNzczMjBiZjU3MjUwZWQ4YmY3OTMzZWE0M2FjOGVmMmZkNzBkZWZkYyJ9fX0='
  gui:
    slot: 4
    material: CHEST
    name: "&2Térkép megtekintése a GUI felületében"
    lore: |
      &7Előny a jobb kattintási
      viselkedés és egyértelműbb
      ikonok a különböző területeken.

      Hátránya a a GUI eszköztár méretének
      korlátozása és a mobilitás korlátozása.