title: "&8-=( &2Champion Settings &8)=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bUpgrade Equipment"
    material: DIAMOND_CHESTPLATE
    lore:
      - "&7Improve your champions"
      - "armor and weapon with each upgrade."
      - ""
      - "&2Level&8: &6%level%"
      - "&2Cost&8: &6%cost%"
    slot: 0
  change:
    name: "&6Change"
    material: DIAMOND_SWORD
    lore:
      - "&7Change your champion type."
    slot: 1

  back:
    name: "&2Back"
    material: BARRIER
    lore:
      - "&6Go back to champion upgrades."
    slot: 4