title: "&cMap Settings"
type: HOPPER

options:
  scoreboard:
    slot: 0
    material: PAPER
    lore: |
      &7Shows the kingdom map as a scoreboard
      which is much more convenient than
      auto map mode and updates automatically.

      The disadvantage is that
      it takes a huge portion of your screen
      and you must memorize the symbols and
      colors and what they mean.

      This option resets if you leave.
    enabled:
      condition: scoreboard_enabled
      name: "{$enabled} Toggle Scoreboard"
      glow: true
    else:
      name: "{$disabled} Toggle Scoreboard"
  reset:
    slot: 1
    material: PLAYER_HEAD
    name: '&4Reset Settings'

    # https://minecraft-heads.com/custom-heads/alphabet/45282-redstone-block-refresh
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzA1ZWI3ZTA0ODg2ODMyNTRlZGI2NzgyYzVkYjhkMjdjZDA3OGU3ODRkZTJkY2RjZDI1Y2UwODY0ZGZhYmQzOCJ9fX0='
  resize:
    slot: 2
    material: PLAYER_HEAD
    name: '&2Resize'
    lore:
      - "&7Resize your own map &awidth &7and &aheight"
      - "&7Your current size&8: &2%kingdoms_map_width%&7, &2%kingdoms_map_height%"

    # https://minecraft-heads.com/custom-heads/decoration/49973-globe
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODc5ZTU0Y2JlODc4NjdkMTRiMmZiZGYzZjE4NzA4OTQzNTIwNDhkZmVjZDk2Mjg0NmRlYTg5M2IyMTU0Yzg1In19fQ=='
  auto:
    slot: 3
    material: PLAYER_HEAD
    lore:
      - "&7The map keeps appearing automatically"
      - "as you walk to different lands."

    enabled:
      condition: 'auto_map_enabled'
      name: "{$enabled} Auto"
      # https://minecraft-heads.com/custom-heads/alphabet/21774-green-checkmark
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDMxMmNhNDYzMmRlZjVmZmFmMmViMGQ5ZDdjYzdiNTVhNTBjNGUzOTIwZDkwMzcyYWFiMTQwNzgxZjVkZmJjNCJ9fX0='
    else:
      name: "{$disabled} Auto"
      # https://minecraft-heads.com/custom-heads/miscellaneous/44761-x
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDdhY2ZmNThjMjExZTQ2ODA2ZDRhYzlhNzczMjBiZjU3MjUwZWQ4YmY3OTMzZWE0M2FjOGVmMmZkNzBkZWZkYyJ9fX0='
  gui:
    slot: 4
    material: CHEST
    name: "&2See the map in a GUI"
    lore: |
      &7Advantages would be better
      clicking behavior and clearer
      icons for different lands.

      Disadvantages would be the
      limit of GUI inventory size
      and limiting your mobility.