title: "{$sep}-=( &7Налаштування {$sep})=-"
rows: 6
sound: ITEM_BOOK_PAGE_TURN

options:
  back:
    posx: 1
    posy: 1
    material: PLAYER_HEAD
    name: '&2Назад'
    lore: [ '&6Повернутися до головного меню Nexus.' ]
    skull: "{$gui-back}"
  light-blue-stained-glass-pane:
    slots: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 21, 23, 26, 27, 29, 30, 31, 32, 33, 35, 36, 39, 41, 44, 45, 53 ]
    material: LIGHT_BLUE_STAINED_GLASS_PANE
    name: ''
  public-home:
    posx: 3
    posy: 5
    material: DARK_OAK_DOOR
    name: "{$s}Публічний Дім{$colon} %kingdoms_bool_nation_home_is_public%"
    lore: |
      &7Коли ваш дім публічний, будь-хто
      може телепортуватися до нього, використовуючи
      {$p}/k nation home %kingdoms_nation_name%
  tax:
    posx: 7
    posy: 5
    material: PAPER
    name: '&6Податок'
    lore: |
      &7Змініть податки вашої нації
      для учасників.

      &6Рівняння Податку Учасника{$colon}
      &2%tax_equation%
      &6Ваш Податок Учасника{$colon} &2$%fancy@kingdoms_nation_tax%

      &6Податок Серверу Нації{$colon} &2$%fancy@kingdoms_nation_tax%
  blue-stained-glass-pane:
    slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 25, 28, 34, 37, 43, 46, 47, 48, 49, 50, 51, 52 ]
    material: BLUE_STAINED_GLASS_PANE
    name: ''
  relations:
    posx: 3
    posy: 3
    material: WRITABLE_BOOK
    name: '&6Відносини'
    lore: |
      &7Змініть атрибути відносин
      з іншими націями.

      {$sep}[&e!{$sep}] {$es}Деякі атрибути
      працюють, якщо обидві нації мають
      активовану атрибут для відносин.

      Наприклад, якщо у вас є атрибут
      {$e}БУДІВНИЦТВО {$es}активований для союзників,
      але ви намагаєтеся будувати на землі союзника, який не
      має активованого атрибуту {$e}БУДІВНИЦТВО {$es}для союзників,
      це не працюватиме. Вони також не зможуть
      будувати на вашій території.
  flag:
    posx: 5
    posy: 3
    material: BLACK_BANNER
    name: '&6Прапор'
    lore: |
      &7Встановіть прапор вашої
      нації для онлайн-карт.
      Клацніть, щоб побачити URL вашого прапора.
      Це не оновить карту миттєво.
  color:
    posx: 5
    posy: 5
    material: LIME_DYE
    name: '&6Колір{$colon} &c%r%&7, &2%g%&7, &9%b% &7(%hex@kingdoms_nation_color%%kingdoms_nation_color%&7)'
    lore: |
      &7Встановіть колір вашого маркера нації
      для чату та онлайн-карті земель.
  shields:
    posx: 7
    posy: 3
    material: SHIELD
    name: '&6Щит{$colon} &2%time@kingdoms_nation_shield_time_left%'
    lore: |
      &7Придбайте щит для вашої
      нації, щоб захистити ваше королівство
      від нападів.

      Учасники королівства, які нападають, коли
      включені національні щити, тимчасово втратять
      доступ до національного щита.