title: "&8-=( &7Ustawienia &8)=-"
rows: 6
sound: ITEM_BOOK_PAGE_TURN

options:
  back:
    posx: 1
    posy: 1
    material: PLAYER_HEAD
    name: '&2Powrót'
    lore: [ '&6Wróć do menu Nexus.' ]
    skull: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19
  light-blue-stained-glass-pane:
    slots: [ 1, 2, 6, 7, 8, 9, 17, 18, 21, 23, 26, 27, 29, 30, 31, 32, 33, 35, 36, 39, 41, 44, 45, 53 ]
    material: LIGHT_BLUE_STAINED_GLASS_PANE
    name: ''
  public-home:
    posx: 4
    posy: 1
    material: DARK_OAK_DOOR
    name: "{$s}Publiczny Dom{$colon} %kingdoms_bool_kingdom_home_is_public%"
    lore: |
      &7Gdy twój dom jest publiczny, każdy
      może teleportować się do niego używając
      {$p}/k home %kingdoms_kingdom_name%
  hidden:
    posx: 5
    posy: 1
    material: POTION
    color: 818595
    name: "{$s}Ukryty{$colon} %kingdoms_bool_kingdom_is_hidden%"
    lore: |
      &7Ukryte królestwa nie są wyświetlane
      na {$p}/k map &7i na mapach online.
  tax:
    posx: 6
    posy: 1
    material: PAPER
    name: '&6Podatki'
    lore: |
      &7Zmień podatki w swoim królestwie
      dla członków.

      &6Podatek Dla Członków{$colon}
      &2%tax_equation%
      &6Twój Osobisty Podatek{$colon} &2$%fancy@kingdoms_tax%

      &6Podatek Królestwa{$colon} &2$%fancy@kingdoms_kingdom_tax%
  blue-stained-glass-pane:
    slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 25, 28, 34, 37, 43, 46, 47, 48, 49, 50, 51, 52 ]
    material: BLUE_STAINED_GLASS_PANE
    name: ''
  relations:
    posx: 3
    posy: 3
    material: WRITABLE_BOOK
    name: '&6Relacje'
    lore: |
      &7Zmień atrybuty relacji
      z innymi królestwami.

      {$sep}[&e!{$sep}] {$es}Aby niektóre atrybuty działały,
      oba królestwa muszą mieć
      atrybut włączony dla tej relacji.

      Na przykład, jeśli masz atrybut {$e}BUDOWA {$es}
      włączony dla sojuszników, ale próbujesz
      budować na terytorium sojusznika, który nie ma
      atrybutu {$e}BUDOWA {$es} włączonego dla sojuszników,
      to nie zadziała. Oni też nie będą mogli
      budować na twoim terytorium.
  flag:
    posx: 5
    posy: 3
    material: BLACK_BANNER
    name: '&6Flaga'
    lore: |
      &7Ustaw flagę swojego królestwa na Dynmapie.
      Kliknij, aby zobaczyć URL twojej flagi.
      To nie aktualizuje mapy od razu.
  pacifism:
    posx: 7
    posy: 3
    material: END_CRYSTAL
    name: '&6Pacifista{$colon} %kingdoms_bool_kingdom_is_pacifist%'
    lore: |
      &7Gdy jesteś w trybie pacifisty,
      twoje królestwo nie może najechać
      ani nie może być najechane przez inne królestwa.

      Jeśli najdziesz królestwo, nie będziesz mógł wrócić
      do trybu pacifisty przez tydzień.

      &2Czas Odnowienia{$colon} &6%pacifism_cooldown%
  invites:
    posx: 3
    posy: 5
    material: BOOK
    name: '&6Wymaga Zaproszenia{$colon} %kingdoms_bool_kingdom_requires_invite%'
    lore: |
      &7Gdy jest wyłączony, każdy może
      dołączyć do tego królestwa bez potrzeby
      zaproszenia za pomocą {$p}/k join %kingdoms_kingdom_name%
  color:
    posx: 5
    posy: 5
    material: LIME_DYE
    name: '&6Kolor{$colon} &c%r%&7, &2%g%&7, &9%b% &7(%hex@kingdoms_kingdom_color%%kingdoms_kingdom_color%&7)'
    lore: |
      &7Ustaw kolor znacznika swojego królestwa
      na czacie i mapach online terytorium.
  shields:
    posx: 7
    posy: 5
    material: SHIELD
    name: '&6Tarcza{$colon} &2%time@kingdoms_shield_time_left%'
    lore: |
      &7Kup tarczę dla swojego
      królestwa, aby chronić je
      przed najazdami.
