title: "{$sep}-=( &7Налаштування {$sep})=-"
rows: 6
sound: ITEM_BOOK_PAGE_TURN

options:
  back:
    posx: 1
    posy: 1
    material: PLAYER_HEAD
    name: '&2Назад'
    lore: [ '&6Повернутися до головного меню.' ]
    skull: "{$gui-back}"
  light-blue-stained-glass-pane:
    slots: [ 1, 2, 6, 7, 8, 9, 17, 18, 21, 23, 26, 27, 29, 30, 31, 32, 33, 35, 36, 39, 41, 44, 45, 53 ]
    material: LIGHT_BLUE_STAINED_GLASS_PANE
    name: ''
  public-home:
    posx: 4
    posy: 1
    material: DARK_OAK_DOOR
    name: "{$s}Публічний Дім{$colon} %kingdoms_bool_kingdom_home_is_public%"
    lore: |
      &7Коли ваш дім є публічним, будь-хто
      може переміщатися до нього, використовуючи
      {$p}/k home %kingdoms_kingdom_name%
  hidden:
    posx: 5
    posy: 1
    material: POTION
    color: 818595
    name: "{$s}Приховане Королівство{$colon} %kingdoms_bool_kingdom_is_hidden%"
    lore: |
      &7Приховані королівства не відображаються
      на карті {$p}/k &7та в інтернет-картах.
  tax:
    posx: 6
    posy: 1
    material: PAPER
    name: '&6Податок'
    lore: |
      &7Змініть податки у вашому королівстві
      для учасників.

      &6Рівняння Податку для Учасників{$colon}
      &2%tax_equation%
      &6Ваш Особистий Податок{$colon} &2$%fancy@kingdoms_tax%

      &6Податок Королівства{$colon} &2$%fancy@kingdoms_kingdom_tax%
  blue-stained-glass-pane:
    slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 25, 28, 34, 37, 43, 46, 47, 48, 49, 50, 51, 52 ]
    material: BLUE_STAINED_GLASS_PANE
    name: ''
  relations:
    posx: 3
    posy: 3
    material: WRITABLE_BOOK
    name: '&6Відносини'
    lore: |
      &7Змініть атрибути вашого відношення
      до інших королівств.

      {$sep}[&e!{$sep}] {$es}Для роботи деяких атрибутів
      обидві королівства повинні мати
      включений атрибут для відношення.

      Наприклад, якщо у вас включений 
      атрибут {$e}БУДІВНИЦТВО{$es} для союзників, але ви намагаєтеся
      будувати на території союзника, у якгого він вимкнений
      Ні ви не вони не зможете будувати.
  flag:
    posx: 5
    posy: 3
    material: BLACK_BANNER
    name: '&6Прапор'
    lore: |
      &7Встановіть прапор вашого королівства для Dynmap.
      Клацніть, щоб побачити URL вашого прапора.
      Це не оновить карту миттєво.
  pacifism:
    posx: 7
    posy: 3
    material: END_CRYSTAL
    name: '&6Пацифізм{$colon} %kingdoms_bool_kingdom_is_pacifist%'
    lore: |
      &7Коли ви знаходитесь у режимі пацифізму,
      ваше королівство не може вторгатися
      і не може бути вторгнуте іншими королівствами.

      Якщо ви вторгнетесь у королівство, ви не зможете
      повернутися в режим пацифізму протягом тижня.

      &2Час відновлення{$colon} &6%pacifism_cooldown%
  invites:
    posx: 3
    posy: 5
    material: BOOK
    name: '&6Потрібне Запрошення{$colon} %kingdoms_bool_kingdom_requires_invite%'
    lore: |
      &7Коли це вимкнено, будь-хто може
      приєднатися до цього королівства без потреби
      в запрошенні за допомогою {$p}/k join %kingdoms_kingdom_name%
  color:
    posx: 5
    posy: 5
    material: LIME_DYE
    name: '&6Колір{$colon} &c%r%&7, &2%g%&7, &9%b% &7(%hex@kingdoms_kingdom_color%%kingdoms_kingdom_color%&7)'
    lore: |
      &7Встановіть колір маркера вашого королівства
      для чату та онлайн-карт території.
  shields:
    posx: 7
    posy: 5
    material: SHIELD
    name: '&6Щит{$colon} &2%time@kingdoms_shield_time_left%'
    lore: |
      &7Придбайте щит для вашого
      королівства, щоб захистити його
      від вторгнень.
