title: "&8-=( &7Settings &8)=-"
rows: 6
sound: ITEM_BOOK_PAGE_TURN

options:
  back:
    posx: 1
    posy: 1
    material: PLAYER_HEAD
    name: '&2Back'
    lore: [ '&6Go back to nexus menu.' ]
    skull: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19
  light-blue-stained-glass-pane:
    slots: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 21, 23, 26, 27, 29, 30, 31, 32, 33, 35, 36, 39, 41, 44, 45, 53 ]
    material: LIGHT_BLUE_STAINED_GLASS_PANE
    name: ''
  public-home:
    posx: 3
    posy: 5
    material: DARK_OAK_DOOR
    name: "{$s}Public Home{$sep}: %kingdoms_bool_nation_home_is_public%"
    lore: |
      &7When your home is public, anyone
      can teleport to it using
      {$p}/k nation home %kingdoms_nation_name%
  tax:
    posx: 7
    posy: 5
    material: PAPER
    name: '&6Tax'
    lore: |
      &7Change your nation taxes
      for members.

      &6Member Tax Equation&8:
      &2%tax_equation%
      &6Your Member Tax&8: &2$%kingdoms_fancy_nation_tax%

      &6Nation Server Tax&8: &2$%kingdoms_fancy_nation_tax%
  blue-stained-glass-pane:
    slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 25, 28, 34, 37, 43, 46, 47, 48, 49, 50, 51, 52 ]
    material: BLUE_STAINED_GLASS_PANE
    name: ''
  relations:
    posx: 3
    posy: 3
    material: WRITABLE_BOOK
    name: '&6Relations'
    lore: |
      &7Change your relation attributes
      for other nations.

      {$sep}[&e!{$sep}] {$es}In order for some attributes
      to work, both kingdoms need to have the
      attribute enabled for the relationship.

      For example, if you have {$e}BUILD {$es}attribute
      enabled for allies, but you're trying to
      build in an ally's land that doesn't
      have {$e}BUILD {$es}attribute enabled for allies,
      this won't work. They won't be able to
      build in your land either.
  flag:
    posx: 5
    posy: 3
    material: BLACK_BANNER
    name: '&6Flag'
    lore: |
      &7Set your nation's flag for online maps.
      Click to see your flag URL.
      This won't update the map instantly.
  color:
    posx: 5
    posy: 5
    material: LIME_DYE
    name: '&6Color&8: &c%r%&7, &2%g%&7, &9%b% &7(%kingdoms_nation_color@hex%%kingdoms_nation_color%&7)'
    lore: |
      &7Set your nation marker
      color for chat and online land maps.
  shields:
    posx: 7
    posy: 3
    material: SHIELD
    name: '&6Shield&8: &2%kingdoms_time_nation_shield_time_left%'
    lore: |
      &7Buy a shield for your
      nation to protect your kingdom
      against invades.

      Kingdom members who invade when
      nation shields are enabled, will
      temporarily lose access to nation's
      shield.